// ─── Overview Stats ───────────────────────────────────────────────────────────
export const overviewStats = [
  { isCounter: true,  value: 60,  suffix: '+',     label: 'Features launched 0→1' },
  { isCounter: false, display: '2 teams',            label: 'Managed as sole PM' },
  { isCounter: true,  value: 20, prefix: '~', suffix: 'x',  label: 'Growth in monthly flow executions since launch' },
  { isCounter: true,  value: 53,  suffix: '%',      label: 'Company adoption in 4 wks (Rebooking)' },
  { isCounter: false, display: '2.5 yrs',           label: 'At Mangomint' },
  { isCounter: false, display: '3 soon',            label: 'Major launches Spring 2026' },
]

// ─── Featured Feature Launches (open full-screen modal) ───────────────────────
export const featuredFeatures = [
  {
    id: 'flows',
    name: 'Flows',
    category: 'Communication Automation',
    tagline: 'Turn every appointment into a retention machine.',
    metrics: [
      { value: '14,000+', label: 'Active flows built' },
      { value: '$540k+',  label: 'Revenue generated in 18 months' },
    ],
    problem:
      'Salons and spas were losing clients between visits with no automated way to follow up after appointments, send rebooking nudges, or trigger campaigns — leaving retention entirely to manual staff effort.',
    solution:
      'An end-to-end communication automation engine with 13 trigger events supporting SMS, email, delays, conditions, and account balance credits. Includes a full visual flow builder with pre-built templates for the most common retention moments.',
    howItWorks:
      'Businesses build flows in a drag-and-drop editor: choose a trigger (e.g. Appointment Completed), add action steps (SMS, email, delay, condition branch, account credit), and publish. Flows run automatically for every matching event going forward.',
    quote: {
      text: 'One customer generated $11,000 in revenue from flows that cost just $389 to send.',
      attribution: 'Mangomint customer case study',
    },
    announcementUrl: 'https://www.mangomint.com/updates/?page=10#introducing-automated-flows-in-mangomint',
    screenshotFile: 'Screen Shot 2026-04-03 at 11.44.41 AM.png',
  },
  {
    id: 'offers',
    name: 'Offers',
    category: 'Rule-Based Discounting',
    tagline: 'Native promotions that follow your business rules — not just blanket discounts.',
    metrics: [
      { value: '24,000+', label: 'Offers created' },
      { value: '66%',     label: 'Customer base adoption' },
    ],
    problem:
      'Mangomint had no native discount or offer system. Businesses couldn\'t run promotions, first-visit offers, or loyalty perks without manual workarounds at checkout — limiting acquisition, retention, and revenue opportunities.',
    solution:
      'A full Offers app with flexible criteria: first-time clients only, specific services or providers, minimum sale amounts, membership-holder limits, one-use-per-client restrictions, and automatic online application at booking.',
    howItWorks:
      'Admins configure offer rules in a structured form: select eligibility criteria, set discount type (% or flat), define expiry and usage limits, and choose how it applies (staff-applied, online code, or automatic trigger). At checkout, the system auto-applies qualifying offers. Two new reports — Offers Usage and Offers Summary — track performance.',
    quote: {
      text: '23,000 activated offers across approximately 3,800 companies within the first year.',
      attribution: 'Mangomint internal data',
    },
    announcementUrl: 'https://www.mangomint.com/updates/?page=9#offers-discounts',
    screenshotFile: 'Screen Shot 2026-04-03 at 11.45.16 AM.png',
  },
  {
    id: 'group-bookings',
    name: 'Group Bookings',
    category: 'Scheduling',
    tagline: 'Book a whole party — automatically, without double-booking.',
    metrics: [
      { value: '41,000+', label: 'Group appointments booked' },
      { value: 'June 2025', label: 'Launch date' },
    ],
    problem:
      'Group appointments — bachelorette parties, family spa days, couples treatments — required manual scheduling workarounds. Staff had to coordinate multiple booking slots by hand, with constant risk of double-booking and a high call volume.',
    solution:
      'Supports up to 5 guests with up to 4 services each. Smart scheduling finds concurrent start times across all staff, and smart provider filtering ensures no provider is double-booked.',
    howItWorks:
      'Clients select "Group Booking" online, add guests, choose services for each person, and the system automatically finds the earliest available slot where all providers are free simultaneously. Staff can also create group appointments from the calendar.',
    quote: {
      text: 'Clients can now book a full bachelorette party experience without a single phone call.',
      attribution: 'Mangomint customer feedback',
    },
    announcementUrl: 'https://www.mangomint.com/updates/?page=7#group-bookings-are-here',
    screenshotFile: 'Screen Shot 2026-04-03 at 11.45.46 AM.png',
  },
]

// ─── Carousel Features ─────────────────────────────────────────────────────────
// Sorted: features WITH announcementUrl first, features WITHOUT last.

export const carouselFeatures = [
  // ── WITH announcement links ────────────────────────────────────────────────
  {
    id: 'rebooking',
    name: 'Internal Rebooking',
    category: 'Retention',
    emoji: '🔁',
    problem: 'No fast way for staff to rebook clients — it required manually hunting for availability with nothing pre-filled, costing time and reducing rebooking rates.',
    howItWorks: 'Staff can rebook from 3 entry points: after checkout, from the calendar "..." menu, or from a client\'s past appointment card. Quick-jump buttons skip to convenient calendar spots, and the sidebar pre-fills client info, service, and customizations.',
    metrics: [
      { value: '37,284', label: 'Rebookings in 4 weeks' },
      { value: '53.4%',  label: 'Company adoption' },
    ],
    quote: '"This was the one feature that when I joined Mangomint 4 years ago I could not comprehend why we didn\'t have it." — Mere Brooks (Support)',
    announcementUrl: 'https://www.mangomint.com/updates/#rebook-appointments-in-seconds',
  },
  {
    id: 'membership-early-renewal',
    name: 'Membership Early Renewal',
    category: 'Memberships',
    emoji: '🔄',
    problem: 'Clients who\'d used their current-period benefits had no clean path to access their next period early. Staff were exploiting the pause flow as a workaround, which was then closed off.',
    howItWorks: 'A new "Renew Early..." option in the client membership menu shows the charge amount and updated billing date. Immediate payment processing; billing schedule resets from the renewal date.',
    metrics: [
      { value: 'Feb 2026', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/#renew-client-memberships-early',
  },
  {
    id: 'gift-card-checkout',
    name: 'Gift Card Improvements at Checkout',
    category: 'Gift Cards',
    emoji: '🎁',
    problem: 'Staff couldn\'t sell gift card promotions at the point of sale, and assigning a recipient required a separate post-checkout step — adding friction during busy sales moments.',
    howItWorks: 'Staff can select any active promotion at checkout with auto-filled values, and optionally assign an owner/recipient inline. Gift card numbers are now hyperlinked in the sale for easy navigation.',
    metrics: [
      { value: 'Feb 2026', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/#gift-cards-are-now-easier-to-sell',
  },
  {
    id: 'product-commission-overrides',
    name: 'Product Commission Overrides',
    category: 'Payroll',
    emoji: '💰',
    problem: 'No way to set different commission rates per product or category for individual staff members — businesses couldn\'t protect margins on high-cost products or incentivize specific sales.',
    howItWorks: 'Admins layer product-specific or category-specific commission overrides per staff member. Most specific rate wins (product > category > default). Configured in Staff Members > Compensation > Product Commission.',
    metrics: [
      { value: '561', label: 'Overrides created post-launch' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=2#more-flexible-product-commissions-are-here',
  },
  {
    id: 'flow-triggers-package-client',
    name: 'Flow Triggers: Package Sold & Client Created',
    category: 'Flows',
    emoji: '🚀',
    problem: 'No automation for following up with package buyers who didn\'t book, or for alerting staff when a prospect dropped off during online booking.',
    howItWorks: '"Package Sold" fires on purchase. "Client Created" fires when a new profile is created, with a filter by source (staff, online, form submission) to target abandoned bookings or new client welcomes.',
    metrics: [
      { value: '2', label: 'New trigger types' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=2#new-flow-triggers-package-sold-client-created',
  },
  {
    id: 'export-all-forms',
    name: 'Export All Client Form Submissions',
    category: 'Forms',
    emoji: '📤',
    problem: 'Medspas had no way to bulk-export a client\'s full form history for compliance or insurance purposes — requiring manual screenshot-by-screenshot workarounds.',
    howItWorks: 'Admins can export all form submissions for a specific client as a single organized zip file via Clients > Client Details > "..." > "Export All Forms."',
    metrics: [
      { value: 'Jan 2026', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=2#export-all-client-forms-as-a-zip-file',
  },
  {
    id: 'gift-card-promo-reordering',
    name: 'Gift Card Promotion Reordering',
    category: 'Gift Cards',
    emoji: '🔃',
    problem: 'Gift card promotions displayed in a fixed order online with no way to surface top or seasonal promos first — burying high-priority offers.',
    howItWorks: 'Admins drag to reorder gift card promotions to control their online display sequence.',
    metrics: [
      { value: 'Jan 2026', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=2#rearrange-gift-card-promotions',
  },
  {
    id: 'flow-trigger-negation',
    name: 'Flow Trigger Negation',
    category: 'Flows',
    emoji: '🚫',
    problem: 'Negative filtering was only possible after a flow triggered — customers couldn\'t exclude conditions at the trigger step itself, causing unnecessary runs and cluttered stats.',
    howItWorks: 'Conditions on the trigger step can now be negated (e.g., "appointment doesn\'t have [service]"). Positive and negative conditions can be mixed. All filters within a negated condition are also negated.',
    metrics: [
      { value: 'Dec 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=3#flows-improvement-exclude-clients-from-entering-a-flow',
  },
  {
    id: 'payroll-staff-overview',
    name: 'Payroll Staff Member Overview',
    category: 'Payroll',
    emoji: '👥',
    problem: 'Payroll admins had to click into each staff profile, open the Compensation tab, and search manually to check onboarding status or payment history — costing time during year-end payroll adoption push.',
    howItWorks: 'A new Staff Member Overview table (Settings > Business Setup > Payroll > View Staff Members) shows onboarding status, payroll settings, and full payment history for all staff in one place.',
    metrics: [
      { value: 'Dec 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=3#new-in-payroll-processing-staff-overview-list',
  },
  {
    id: 'form-submission-export',
    name: 'Form Submission Export & High-Res Image Download',
    category: 'Forms',
    emoji: '📑',
    problem: 'Users couldn\'t export a complete form submission for record-keeping. Saving one high-res image required exporting the entire form.',
    howItWorks: '(1) Full form export creates a print-ready file with all fields, images, markups, and metadata. (2) Quick download button on each image for individual high-res downloads.',
    metrics: [
      { value: '136', label: 'Intercom requests' },
      { value: 'Oct 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=3#download-entire-form-submissions-or-specific-images',
  },
  {
    id: 'archived-staff-reports',
    name: 'Archived Staff in Reports',
    category: 'Reporting',
    emoji: '📊',
    problem: 'Five key reports didn\'t include data for archived staff, making historical reporting incomplete after employee turnover.',
    howItWorks: '"Select specific staff members" filter now includes archived staff in 5 reports: Service & Product Sales by Staff, Sales Summary, BI: Appointments, BI: Sales, and Client Retention.',
    metrics: [
      { value: '5', label: 'Reports updated' },
      { value: 'Oct 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=5#view-reports-for-archived-staff-members',
  },
  {
    id: 'book-same-service-multiple-times',
    name: 'Book Same Service Multiple Times',
    category: 'Online Booking',
    emoji: '🔁',
    problem: 'Clients could stack the same service internally but not through online booking — blocking stacked treatment formats like double massages or variable-length facials.',
    howItWorks: 'New toggle in Settings > Online Booking > Preferences allows clients to book the same service multiple times in one appointment.',
    metrics: [
      { value: 'Oct 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=6#clients-can-now-book-the-same-service-multiple-times',
  },
  {
    id: 'membership-pause',
    name: 'Membership Pause',
    category: 'Memberships',
    emoji: '⏸️',
    problem: 'Customers had no way to put a membership on hold — they had to cancel and restart, losing history and perks. A workaround via the pause flow was being exploited for early renewals.',
    howItWorks: 'Memberships can be paused indefinitely or with a specific resume date. Auto-resumes and bills on the resume date. Clients lose perks while paused but keep unused credits until expiry. Automated message sent on pause.',
    metrics: [
      { value: '147+',    label: 'Intercom requests at launch' },
      { value: 'Aug 2025', label: 'Launch date' },
    ],
    quote: '"Incoming chat: I ask, and I shall receive! cool! I shall investigate it now. Thanks! You guys rock!" — Customer reaction after launch',
    announcementUrl: 'https://www.mangomint.com/updates/?page=6#pausing-memberships-is-here',
  },
  {
    id: 'account-balance-memberships',
    name: 'Account Balance Memberships',
    category: 'Memberships',
    emoji: '💳',
    problem: 'Existing membership types only supported service credits. Customers wanted a model where clients pay monthly and receive rolling account balance credits usable toward any service or product.',
    howItWorks: 'New membership type that credits a dollar amount to a client\'s account balance each billing cycle. Supports charging a different price vs. credit amount (e.g., pay $100, get $120 credit). Unused balances roll over. Launched alongside a refreshed membership & package setup UI.',
    metrics: [
      { value: 'Jul 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=6#new-membership-option-add-funds-to-client-account-balances',
  },
  {
    id: 'changelog-in-app',
    name: 'Public Changelog + In-App Announcements',
    category: 'Platform',
    emoji: '📣',
    problem: 'Product updates were hosted on a hard-to-find URL with no direct links from the main site, no in-app experience, no push notifications, and no targeting by user type or vertical.',
    howItWorks: 'New changelog at mangomint.com/updates with old URL redirecting. "What\'s New" button opens an in-app sidebar with announcements segmented by user role (admin, non-admin, billing user) and vertical. Red dot notification indicator on mobile and web.',
    metrics: [
      { value: 'Aug 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates',
  },
  {
    id: 'gift-card-search',
    name: 'Gift Card Search by Client Name',
    category: 'Gift Cards',
    emoji: '🔍',
    problem: 'Gift card search only worked by gift card number — a pain point when staff didn\'t have that info on hand and needed to help a client at checkout.',
    howItWorks: 'Typing a client name now returns gift cards tied to them as purchaser or recipient. Number-only searches still work as before.',
    metrics: [
      { value: '15+',     label: 'Intercom requests' },
      { value: 'Jun 2025', label: 'Launch date' },
    ],
    quote: '"Is there a way to search gift cards by purchaser\'s name? It\'s very difficult to help a client find a gift when they don\'t have the voucher number."',
    announcementUrl: 'https://www.mangomint.com/updates/?page=6#search-gift-cards-by-client-name',
  },
  {
    id: 'receipt-link-merge-tag',
    name: 'Receipt Link Merge Tag for Flows',
    category: 'Flows',
    emoji: '🧾',
    problem: 'Businesses could send receipt links via email automations but not via text message — missing a major opportunity for automated post-checkout communication.',
    howItWorks: 'A new [Receipt Link] merge tag is available in the Sale Closed flow trigger. A pre-built flow was added to make this plug-and-play for the holiday season.',
    metrics: [
      { value: 'Nov 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=4#text-receipts-to-clients-using-flows',
  },
  {
    id: 'email-campaign-filters',
    name: 'Email Campaign Filters: Membership & Package',
    category: 'Marketing',
    emoji: '🔖',
    problem: 'No way to segment email campaigns by package ownership, limiting targeting for membership/package promotions during Black Friday and holiday periods.',
    howItWorks: 'Three new filters added: "Has no membership," "Has package," "Has no package." Enables precise targeting for membership upgrade and package promotions.',
    metrics: [
      { value: '3',        label: 'New audience filters' },
      { value: 'Nov 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=4#new-audience-filters-for-email-campaigns',
  },
  {
    id: 'quickbooks-payroll-sync',
    name: 'QuickBooks Payroll Sync',
    category: 'Payroll',
    emoji: '📊',
    problem: 'After running payroll, customers had to manually do all bookkeeping — splitting out wages, tips, taxes, and benefits across their accounting software.',
    howItWorks: 'Payroll data syncs directly to QuickBooks Online, closing the loop between payroll and accounting. Saves hours of manual bookkeeping per pay run.',
    metrics: [
      { value: 'Nov 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=4#quickbooks-payroll-sync-is-here',
  },
  {
    id: 'payroll-journal-downloads',
    name: 'Payroll Journal Downloads (Any Date Range)',
    category: 'Payroll',
    emoji: '📂',
    problem: 'Payroll journals were only available per individual pay run; pulling aggregated year-end reports required contacting Support.',
    howItWorks: 'Customers can download detailed journals for any quarter, year, or custom date range directly in the app — significantly reducing support burden heading into year-end.',
    metrics: [
      { value: 'Nov 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=4#download-payroll-journals-with-mangomint-payroll',
  },
  {
    id: 'gift-card-sales-report',
    name: 'Gift Card Sales Details Report',
    category: 'Reporting',
    emoji: '🗃️',
    problem: 'No report showing which promotions were driving gift card sales or details of specific gift card transactions — making it impossible to track promo performance.',
    howItWorks: 'New report shows all gift card sales in a selected period: sale #, date, client, GC #, promotion used, GC value, price, selling staff. Exportable as PDF or Excel.',
    metrics: [
      { value: 'Nov 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=4#a-new-report-is-here-gift-card-sales-details',
  },
  {
    id: 'new-refunds-experience',
    name: 'New Refunds Experience',
    category: 'Payments',
    emoji: '💸',
    problem: 'The legacy refund flow was broken — multiple steps for something that should be simple, with poor support for commissions, inventory, and reporting. A multi-year infrastructure effort was required before a full rebuild was possible.',
    howItWorks: 'Rebuilt step-by-step refund flow with item-based or amount-based refunds, built-in handling for commissions, inventory, and memberships. Separate refund records, clearer status indicators, and permissions for who can refund and when.',
    metrics: [
      { value: '3+',      label: 'Years in the making' },
      { value: 'Sep 2025', label: 'Full rollout' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=5#refunds-just-got-an-upgrade',
  },
  {
    id: 'marketing-credit-plans',
    name: 'Marketing Credit Subscription Plans',
    category: 'Marketing',
    emoji: '💳',
    problem: 'Customers had to purchase marketing credits as one-time top-ups with no way to set up recurring auto-renewal.',
    howItWorks: 'Customers can add monthly marketing credit plans to their subscription. Plan credits reset each cycle; additional credits can still be purchased separately. Plan credits are used first.',
    metrics: [
      { value: 'Oct 2024', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=9#marketing-credit-subscription-plans',
  },
  {
    id: 'account-balance-flow-images',
    name: 'Add to Account Balance in Flows + Images in SMS',
    category: 'Flows',
    emoji: '💵',
    problem: 'No way to automate adding credits to a client\'s account balance, and flow text messages were text-only with no image support.',
    howItWorks: 'New "Add to account balance" action step in Flows enables automated loyalty rewards. Up to 5 images can be added to Flows text messages with tiered credit pricing.',
    metrics: [
      { value: 'Mar–Apr 2025', label: 'Launch dates' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=6#more-possibilities-with-flows-actions-messaging-visibility',
  },
  {
    id: 'flow-email-merge-tags-send-test',
    name: 'Merge Tags in Email Subjects + Send Test SMS',
    category: 'Flows',
    emoji: '✉️',
    problem: 'Merge tags couldn\'t be used in Flows email subject lines. Testing text message steps required triggering an actual flow run — no sandbox option existed.',
    howItWorks: 'New "+" icon in the email subject text box allows inserting merge tags and emojis directly. New "Send Test" button for SMS steps prompts a phone number and sends a free test without consuming marketing credits.',
    metrics: [
      { value: 'Feb 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=7#send-test-text-messages-improved-email-subject-options',
  },
  {
    id: 'flows-goal-completion',
    name: 'Flows: Goal Completion Toggle & Multiple Goals',
    category: 'Flows',
    emoji: '🎯',
    problem: 'Goals in Flows always stopped the flow when reached — no way to track goal completion and continue the sequence. Only one goal could be tracked.',
    howItWorks: 'New toggle controls whether a goal stops the flow. Multiple goals can now be tracked independently, each with its own stats box in the Statistics tab.',
    metrics: [
      { value: 'Feb 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=7#enhanced-goal-settings-statistics-now-available-for-flows',
  },
  {
    id: 'offers-new-clients',
    name: 'Offers: Limit to New Clients Only',
    category: 'Offers',
    emoji: '🎯',
    problem: 'Offers couldn\'t be restricted to new clients — businesses had no native way to offer first-visit promotions without risk of abuse by existing clients.',
    howItWorks: 'New toggle on Offers limits any promotion to new clients only. Enables targeted acquisition promotions (e.g., 20% off first visit) without worrying about repeat redemption.',
    metrics: [
      { value: 'Feb 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=7#limit-offers-to-new-clients-only',
  },
  {
    id: 'offers-specific-providers',
    name: 'Offers: Limit to Specific Providers',
    category: 'Offers',
    emoji: '🎯',
    problem: 'Service discounts couldn\'t be restricted to specific providers — businesses couldn\'t encourage bookings with newer staff without discounting senior providers.',
    howItWorks: 'New toggle on Offers allows selecting which provider(s) the discount applies to. Enables incentivizing bookings with specific staff without affecting others.',
    metrics: [
      { value: 'Mar 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=7#limit-service-discounts-to-specific-providers',
  },
  {
    id: 'offers-one-use',
    name: 'Offers: Limit to One Use Per Client',
    category: 'Offers',
    emoji: '🎯',
    problem: 'Offers usage couldn\'t be restricted to one use per client, making it difficult to track if a client was reusing an offer they\'d already redeemed.',
    howItWorks: 'New toggle limits any offer to one application per client — enabling truly one-time promotions without manual tracking.',
    metrics: [
      { value: 'Dec 2024', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=8#limit-offers-to-one-use-per-client',
  },
  {
    id: 'package-credits-expire-trigger',
    name: 'Flow Trigger: Before Package Credits Expire',
    category: 'Flows',
    emoji: '📦',
    problem: 'No way to automatically remind clients that their package credits were expiring soon — leading to unused credits, missed bookings, and client frustration.',
    howItWorks: 'Trigger fires a configurable number of days/weeks before package credits expire. Includes two new merge tags: [Package credits remaining] and [Package expiration date].',
    metrics: [
      { value: 'Jan 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=8#flows-will-remind-clients-to-use-their-packages-before-they-expire',
  },
  {
    id: 'payroll-greater-of',
    name: 'Payroll: Greater-Of Compensation Per Period',
    category: 'Payroll',
    emoji: '💵',
    problem: 'The "greater-of" payroll comparison (commissions vs. hourly wages) only worked on a per-day basis — disadvantaging high-commission staff on slower days.',
    howItWorks: 'Admins can now choose to run the greater-of comparison across an entire pay period rather than day-by-day, enabling more accurate and fair compensation for variable-performance staff.',
    metrics: [
      { value: 'Jan 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=8#per-pay-period-greater-of-compensation-type',
  },
  {
    id: 'flows-form-field-filter',
    name: 'Flows: Form Field Response Filter',
    category: 'Flows',
    emoji: '📝',
    problem: 'The "Form Submitted" trigger couldn\'t filter based on specific answers within the form — limiting targeted follow-up based on what a client actually wrote.',
    howItWorks: 'New condition filter for form field responses — supports checking if fields are filled/empty, or filtering for specific values in dropdowns, toggles, and multi-choice fields.',
    metrics: [
      { value: 'Jan 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=8#filter-your-flows-based-on-responses-to-forms',
  },
  {
    id: 'membership-canceled-trigger',
    name: 'Flow Trigger: Membership Canceled',
    category: 'Flows',
    emoji: '🔁',
    problem: 'No way to automatically follow up with clients who canceled their membership — a massive missed win-back opportunity.',
    howItWorks: 'New trigger fires when a client\'s membership is canceled. Supports confirmation messages, cancellation reason surveys, and win-back re-engagement flows.',
    metrics: [
      { value: 'Jan 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=8#new-flows-trigger-membership-canceled',
  },
  {
    id: 'membership-credits-expire-appt-canceled',
    name: 'Flow Triggers: Membership Credits Expiring & Appointment Canceled',
    category: 'Flows',
    emoji: '🔁',
    problem: 'No native way to proactively remind clients of expiring membership credits or automatically follow up after a cancellation.',
    howItWorks: 'Two new triggers + two pre-built flows. "Before membership credits expire" triggers early. "Appointment canceled" fires on cancellation. Also added: service/category filter on the Sale Closed trigger.',
    metrics: [
      { value: 'Oct 2024', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=9#more-ways-to-utilize-automated-flows',
  },
  {
    id: 'flows-run-frequency',
    name: 'Flows: Run Frequency Limit & Incomplete Forms Filter',
    category: 'Flows',
    emoji: '📊',
    problem: 'No way to prevent a flow from running more than once in a given timeframe. No way to conditionally send form reminders only when forms were actually incomplete.',
    howItWorks: 'New setting limits a flow to run once every X weeks/months. New filter checks for uncompleted client forms, with a merge tag for the forms link.',
    metrics: [
      { value: 'Nov 2024', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=9#flows-just-got-more-powerful',
  },
  {
    id: 'client-account-balances',
    name: 'Client Account Balances',
    category: 'Payments',
    emoji: '💳',
    problem: 'No native way to credit a client\'s account with a dollar amount usable across future purchases — limiting loyalty programs, prepay use cases, and automated credit incentives.',
    howItWorks: 'Admins enable Client Account Balances in Advanced Settings. Balances can be added manually or via flows, used at checkout across services, products, and more. Balance history shows memo for each transaction.',
    metrics: [
      { value: 'Dec 2024', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=8#introducing-client-account-balances',
  },
  {
    id: 'offers-membership-only',
    name: 'Offers: Limit to Clients with Memberships',
    category: 'Offers',
    emoji: '🎁',
    problem: 'Offers couldn\'t be restricted to membership holders — making it impossible to run exclusive member promotions without manual vetting at checkout.',
    howItWorks: 'New toggle limits any offer to clients with any active membership, or specific membership types. Can be used as an automatic offer to apply extra member perks at checkout.',
    metrics: [
      { value: 'Dec 2024', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=8#offers-can-now-be-limited-to-clients-with-memberships',
  },
  {
    id: 'online-booking-exclude-staff',
    name: 'Online Booking: Exclude Staff from "Anyone"',
    category: 'Online Booking',
    emoji: '🎯',
    problem: 'Businesses using "Anyone" or gendered provider selection had no way to exclude specific staff from that pool — no workload control without removing staff entirely.',
    howItWorks: 'New setting allows admins to designate specific staff members who should be excluded when clients select a non-specific provider preference online.',
    metrics: [
      { value: 'Jul 2024', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=11#new-online-booking-setting',
  },
  {
    id: 'form-approvals',
    name: 'Form Approvals',
    category: 'Forms',
    emoji: '✅',
    problem: 'No way for a reviewer (e.g., an MD at a medspa) to formally approve or reject form submissions before they were acted upon — a compliance gap for medical wellness businesses.',
    howItWorks: 'Admins can assign reviewers to form templates. Reviewers get notified and can approve/reject submissions directly in the app.',
    metrics: [
      { value: 'Jul 2024', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=11#form-review-and-approvals',
  },
  {
    id: 'save-in-progress-forms',
    name: 'Save In-Progress Forms',
    category: 'Forms',
    emoji: '💾',
    problem: 'If a client or staff member started filling out a form and left before completing it, all progress was lost — especially problematic for long medical intake forms.',
    howItWorks: 'Forms can be saved mid-completion and resumed later from any device.',
    metrics: [
      { value: 'Jun 2024', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=11#save-progress-on-forms',
  },
  {
    id: 'multi-phone-number',
    name: 'Multi-Phone Number Support (2WT)',
    category: 'Messaging',
    emoji: '📞',
    problem: 'Multi-location businesses had to use a single shared phone number for two-way texting across all locations — limiting filtering, push notifications, and local area code matching.',
    howItWorks: 'Each location can now have its own unique sending phone number. Conversations can be filtered by number/location. Customers manage numbers directly in settings.',
    metrics: [
      { value: 'Mar 2024', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=12#use-location-specific-phone-numbers-for-texts-and-automated-messages',
  },
  {
    id: 'custom-email-address',
    name: 'Custom Email Address for Marketing',
    category: 'Marketing',
    emoji: '📧',
    problem: 'All marketing emails sent from Mangomint used a generic Mangomint sending address — preventing businesses from sending from their own domain and reducing deliverability.',
    howItWorks: 'Admins can connect their own domain in Business Setup > Advanced Settings via a guided wizard. Supported for campaigns and automated messages.',
    metrics: [
      { value: 'Mar 2024', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: 'https://www.mangomint.com/updates/?page=13#use-a-custom-email-address-for-your-marketing-emails',
  },
  {
    id: 'online-membership-package-sales',
    name: 'Online Membership & Package Sales',
    category: 'E-Commerce',
    emoji: '🛍️',
    problem: 'Clients couldn\'t buy memberships or packages through online booking — a significant blocker for leads and a churn risk for existing customers.',
    howItWorks: 'Admins enable online sales per plan in a new "Online Sales" tab. Supports ordering, agreements/contracts, direct-link-only listing, client portal visibility, and automated messaging.',
    metrics: [
      { value: '261',     label: 'Intercom requests' },
      { value: 'Aug 2025', label: 'Launch date' },
    ],
    quote: '"260 of them [tagged customers]! If you sort by \'Newest activity\' you can see all the \'Thank you\'s and follow-up questions!"',
    announcementUrl: 'https://www.mangomint.com/updates/?page=4#sell-membership-plans-packages-online',
  },

  // ── WITHOUT announcement links (go last) ──────────────────────────────────
  {
    id: 'payroll-salesforce-sync',
    name: 'Payroll Onboarding Salesforce Sync',
    category: 'Internal Tools',
    emoji: '🤖',
    problem: 'Payroll support staff had to manually update Salesforce during onboarding Zoom calls, splitting their attention and wasting hours per week.',
    howItWorks: 'Payroll onboarding progress in Mangomint automatically syncs to the Salesforce Payroll Onboarding Dashboard every 5 minutes.',
    metrics: [
      { value: '12–14 hrs', label: 'Saved per week' },
      { value: 'Feb 2026',  label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: null,
  },
  {
    id: 'self-serve-payroll-termination',
    name: 'Self-Serve Payroll Staff Termination',
    category: 'Payroll',
    emoji: '🔚',
    problem: 'Terminating a payroll-enrolled staff member was entirely manual — Support had to terminate in Salsa, remove from pay group, disconnect in Mangomint, and update subscription count. Extremely error-prone.',
    howItWorks: 'Admins terminate payroll staff directly in Mangomint, selecting termination type, date, and notes. Payroll seat count and fees update automatically. Only billing users can rehire.',
    metrics: [
      { value: 'Dec 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: null,
  },
  {
    id: 'delete-merge-clients-permission',
    name: '"Can Delete and Merge Clients" Permission',
    category: 'Permissions',
    emoji: '🔐',
    problem: 'Any staff member with access to client contact details could also delete or merge client records — no way to decouple these sensitive actions from basic view access.',
    howItWorks: 'New granular permission separates "delete/merge" from "view client details." Enabling delete/merge auto-locks related view permissions for proper data protection.',
    metrics: [
      { value: 'Nov 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: null,
  },
  {
    id: 'flows-list-filtering',
    name: 'Flows List Filtering',
    category: 'Flows',
    emoji: '🔍',
    problem: 'No way to filter the Flows list, making it hard to find specific flows on accounts with many automations.',
    howItWorks: 'The Flows list is now filterable by status (Draft, Active, Inactive) and trigger type.',
    metrics: [
      { value: 'Oct 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: null,
  },
  {
    id: 'flows-client-total-spend',
    name: 'Flows: Client Total Spend Condition',
    category: 'Flows',
    emoji: '💵',
    problem: 'Only single-sale spend was checkable in Flows. No way to act based on a client\'s cumulative lifetime or period spend.',
    howItWorks: 'New condition checks a client\'s total spend across all historical sales (services, products, gift cards, memberships), with an optional date range filter. Powers loyalty-based automations.',
    metrics: [
      { value: 'Feb 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: null,
  },
  {
    id: 'offers-prepayment-discounts',
    name: 'Offers: Apply Discounts on Prepayments',
    category: 'Offers',
    emoji: '🧾',
    problem: 'Offer codes could be entered during online booking, but the discount wasn\'t applied until in-person checkout — confusing clients who expected to see savings immediately.',
    howItWorks: 'For full deposit bookings, the discount is applied at online checkout. Partial deposits store the code for in-person application. No-deposit bookings unchanged.',
    metrics: [
      { value: 'Feb 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: null,
  },
  {
    id: 'payroll-edit-pay-adjustments',
    name: 'Payroll: Edit Existing Pay Adjustments',
    category: 'Payroll',
    emoji: '💳',
    problem: 'Fixing a pay adjustment required deleting it and creating a new one from scratch — error-prone and time-consuming for admins managing frequent corrections.',
    howItWorks: 'Pay adjustments can now be edited directly without deletion, reducing friction and errors in payroll management.',
    metrics: [
      { value: 'Jan 2025', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: null,
  },
  {
    id: 'payroll-onboarding-digest',
    name: 'Payroll: Onboarding Daily Digest Email',
    category: 'Payroll',
    emoji: '💵',
    problem: 'Admins had no proactive visibility into outstanding payroll onboarding tasks — they had to know to look for them, leading to support escalations.',
    howItWorks: 'Daily digest email at 9am lists all outstanding onboarding tasks until payroll is fully set up. A new per-staff task list in the Compensation tab shows exactly what\'s needed per worker.',
    metrics: [
      { value: 'Oct 2024', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: null,
  },
  {
    id: 'user-delight',
    name: 'User Delight Initiative',
    category: 'Platform',
    emoji: '🎨',
    problem: 'No built-in way to reward and recognize Mangomint users for usage milestones or create moments of delight that reinforced product love.',
    howItWorks: 'Users receive email and iOS push notifications when they reach achievements or receive a gift forwarded from a coworker. Tracked via Sigma dashboard and Slack automation.',
    metrics: [
      { value: 'Oct 2024', label: 'Launch date' },
    ],
    quote: null,
    announcementUrl: null,
  },
]
